In [1]:
import numpy as np

In [2]:
array = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])
print(array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
print(array.ndim)#维度

2


In [4]:
print(array.shape)#形状

(3, 3)


In [5]:
print(array.size)#大小

9


In [6]:
print(array.dtype)#元素属性

int32
