In [1]:
import numpy as np

In [2]:
sample1 = np.random.random((3,2))#生成3行2列从0到1的随机数
print(sample1)

[[0.86708754 0.64208924]
 [0.47110451 0.65090454]
 [0.91982493 0.280307  ]]


In [3]:
sample2 = np.random.normal(size=(3,2))#生成3行2列符合标准正态分布的随机数
print(sample2)

[[ 0.45134746 -0.63467249]
 [-0.05672776  0.66311292]
 [ 0.82098998 -0.01351047]]


In [4]:
sample3 = np.random.randint(0,10,size=(3,2))#生成3行2列从0到10的随机整数
print(sample3)

[[3 8]
 [3 4]
 [2 3]]


In [5]:
np.sum(sample1)# 求和

3.8313177660127766

In [6]:
np.min(sample1)#求最小值

0.280307001949191

In [7]:
np.max(sample1)#求最大值

0.9198249270974059

In [8]:
np.sum(sample1, axis=0)#对矩阵列求和

array([2.25801698, 1.57330079])

In [9]:
np.sum(sample1, axis=1)#对矩阵行求和

array([1.50917678, 1.12200906, 1.20013193])

In [10]:
print(sample1)

[[0.86708754 0.64208924]
 [0.47110451 0.65090454]
 [0.91982493 0.280307  ]]


In [12]:
np.argmin(sample1)#求最小值的索引

5

In [13]:
np.argmax(sample1)#求最大值的索引

4

In [15]:
print(np.mean(sample1))#求平均值
print(sample1.mean())

0.6385529610021294
0.6385529610021294


In [16]:
np.median(sample1)#求所有元素的中位数

0.6464968922540429

In [18]:
np.sqrt(sample1)#开方

array([[0.93117535, 0.80130471],
       [0.68637054, 0.80678655],
       [0.95907504, 0.52944027]])

In [20]:
sample4 = np.random.randint(0,10,size=(1,10))
print(sample4)

[[2 5 3 7 0 4 0 9 5 7]]


In [21]:
np.sort(sample4)#排序

array([[0, 0, 2, 3, 4, 5, 5, 7, 7, 9]])

In [22]:
np.sort(sample1)#对每一行排序

array([[0.64208924, 0.86708754],
       [0.47110451, 0.65090454],
       [0.280307  , 0.91982493]])

In [23]:
np.clip(sample4, 2, 7)#小于2的数变为2，大于7的数变为7

array([[2, 5, 3, 7, 2, 4, 2, 7, 5, 7]])